- name: rsync deployments
  # You may pin to the exact commit or the version.
  # uses: contention/rsync-deployments@10f98a8726e6760601d8818ea6ff812f87bf8a97
  uses: contention/rsync-deployments@v2.0.0
  with:
    # Initial/required rsync flags
    flags: 
    # Exclude flags and directory pairs
    excludes: 
    # The server user
    user: 
    # The deployment target
    host: 
    # The local path to sync
    localpath: 
    # The remote path to sync
    remotepath: 
    # The private key
    deploy_key: 
